apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-python-go-rust-service
  title: Serviço Base em Python, Go ou Rust
  description: Template para criar serviços em Python, Go ou Rust, integrado ao pipeline existente.
  tags:
    - python
    - go
    - rust
    - service
spec:
  owner: devops-team
  type: service
  parameters:
    - title: Configurações do Projeto
      required:
        - projectName
        - language
        - repoVisibility
      properties:
        projectName:
          title: Nome do Projeto
          type: string
          description: Nome do repositório ou serviço.
        language:
          title: Linguagem do Projeto
          type: string
          enum:
            - python
            - go
            - rust
          description: Escolha a linguagem base.
        repoVisibility:
          title: Visibilidade do Repositório
          type: string
          enum:
            - public
            - private
          description: Visibilidade do repositório GitHub.
  steps:
    - id: fetch-template
      name: Buscar Template Base
      action: fetch:template
      input:
        url: ./templates/{{ parameters.language }}-base
        targetPath: .
    - id: process-template
      name: Processar Template
      action: scaffolder:template
    - id: run-validation
      name: Validar Configuração Inicial
      action: run:command
      input:
        workingDirectory: .
        command: |
          if [ "{{ parameters.language }}" = "python" ]; then
            pip install -r requirements.txt && pytest;
          elif [ "{{ parameters.language }}" = "go" ]; then
            go mod tidy && go test ./...;
          elif [ "{{ parameters.language }}" = "rust" ]; then
            cargo test;
          fi
    - id: publish-to-repo
      name: Publicar no GitHub
      action: publish:github
      input:
        repoUrl: github.com/{{ parameters.owner }}/{{ parameters.projectName }}
        repoVisibility: {{ parameters.repoVisibility }}
    - id: register-in-catalog
      name: Registrar no Catálogo
      action: catalog:register
      input:
        location:
          type: url
          target: https://github.com/{{ parameters.owner }}/{{ parameters.projectName }}/blob/main/catalog-info.yaml
  output:
    links:
      - title: Repositório do Projeto
        url: https://github.com/{{ parameters.owner }}/{{ parameters.projectName }}
      - title: Catálogo Backstage
        url: /catalog/default/component/{{ parameters.projectName }}
