apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-service
  title: Criar um Serviço Python
  description: Um template para criar um novo serviço Python com estrutura básica.
  tags:
    - python
    - service
spec:
  owner: devops-team
  type: service
  parameters:
    - title: Configurações do Projeto
      required:
        - projectName
        - repoVisibility
      properties:
        projectName:
          title: Nome do Projeto
          type: string
          description: Nome do serviço Python.
        repoVisibility:
          title: Visibilidade do Repositório
          type: string
          enum:
            - public
            - private
          description: Define a visibilidade do repositório GitHub.

  steps:
    - id: fetch-template
      name: Baixar Template Base
      action: fetch:template
      input:
        url: https://github.com/pedrojbDev/python-template-backstage/archive/main.zip
        targetPath: .

    - id: process-template
      name: Processar Template
      action: scaffolder:template

    - id: publish-to-repo
      name: Criar Repositório no GitHub
      action: publish:github
      input:
        repoUrl: github.com/{{ parameters.owner }}/{{ parameters.projectName }}
        repoVisibility: {{ parameters.repoVisibility }}

    - id: register-in-catalog
      name: Registrar no Catálogo do Backstage
      action: catalog:register
      input:
        location:
          type: url
          target: https://github.com/{{ parameters.owner }}/{{ parameters.projectName }}/blob/main/catalog-info.yaml

  output:
    links:
      - title: Repositório do Projeto
        url: https://github.com/{{ parameters.owner }}/{{ parameters.projectName }}
      - title: Backstage Catalog
        url: /catalog/default/component/{{ parameters.projectName }}
